### PR TITLE
Fixes for banner option

### LINKED ISSUE #14: Banner is not working as expected
There are several issues with banner:

- [ ] banner option is not overriding top level options, it extends it
- [ ] banner in rollup accepts function, while `string` only is expected in plugin

PR is ready, I will submit it soon.

### PR DESCRIPTION
**Pull request by gagoman**
Closes #14 

Short outcome for this PR:

* Rollup options processing is different for API and config file (my case). For config file it first parses it and then passes same options to `generate` ([here](https://github.com/rollup/rollup/blob/ae54071232bb7236faf0848941c857f7c534ae09/bin/src/runRollup.js#L248) and [here](https://github.com/rollup/rollup/blob/ae54071232bb7236faf0848941c857f7c534ae09/bin/src/runRollup.js#L271))
* transformBundle does not receive all set of options ([source](https://github.com/rollup/rollup/blob/ae54071232bb7236faf0848941c857f7c534ae09/src/utils/transformBundle.js#L11)) which was not fully covered by [this test](https://github.com/Comandeer/rollup-plugin-babili/blob/master/tests/index.js#L96)
* there is no way (as I can see right now) to manipulate  `banner` option of `bundle.generate`

I can squash commits if you'd prefer (unsquashed for now to show some failed tests).

Please comment and thank you for a plugin.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -5,19 +5,37 @@ import bannerPlugin from '@comandeer/babel-plugin-banner';
...
+};
+const isFn = ( v ) => {
+	return v != null && typeof v === 'function';
+};
+const isFnOrString = ( v ) => {
+	return isString( v ) || isFn( v );
+};
+
 function babili( options = {} ) {
+	let _banner;
```
Comment (Comandeer) [inline src/index.js]: Well, it's the only thing I don't like: this variable name :D It's easily confusable with later `banner` one and does not really explain the purpose of this variable. Maybe something like `rollupBanner` to indicate that it comes from rollup options?
